# Generated by Django 5.0.6 on 2025-11-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="session_token",
        ),
    ]
